#!/usr/bin/env sh

# Load scripting extension
sudo yabai --load-sa

# Load the scripting extension via yabai
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# Window layout
yabai -m config layout           bsp
yabai -m config window_placement second_child 
yabai -m config window_topmost   off

# Window borders
yabai -m config window_border                off
yabai -m config window_border_width          5
yabai -m config active_window_border_color   0xff8CABC8
yabai -m config normal_window_border_color   0xff434c5e
yabai -m config insert_feedback_color        0xffd75f5f

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    50
yabai -m config bottom_padding 12
yabai -m config left_padding   12
yabai -m config right_padding  12
yabai -m config window_gap     12

# Mouse settings and focus modes 
yabai -m config focus_follows_mouse autoraise 
yabai -m config mouse_follows_focus off 
yabai -m config mouse_modifier      cmd
yabai -m config split_ratio         0.50
yabai -m config auto_balance        off

# tell yabai which apps to ignore
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Settings$"    manage=off
yabai -m rule --add app="^System Preferences$" manage=off
