#!/usr/bin/env python3
# dotman-install v1 -- generated by dotman; edits are overwritten when you update it from the UI.
"""Link the dotfiles in this repo into $HOME on a new machine.

Usage:
    python3 install.py --dry-run   # show what would happen
    python3 install.py             # create symlinks; files in the way are backed up

Needs only Python 3.8+ stdlib. Reads dotman.json next to this script and links
every entry enabled for this OS: ~/<path> -> <repo>/home/<path>.
Anything already at a target is moved to ~/.dotman-backups/<timestamp>/ first.
"""

import argparse
import json
import os
import shutil
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent
HOME = Path.home()


def current_os():
    if sys.platform.startswith("linux"):
        return "linux"
    if sys.platform == "darwin":
        return "macos"
    return sys.platform


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true", help="print the plan, change nothing")
    args = ap.parse_args()

    this_os = current_os()
    entries = json.loads((REPO / "dotman.json").read_text()).get("entries", [])
    backup_root = HOME / ".dotman-backups" / time.strftime("%Y%m%d-%H%M%S")
    counts = {"link": 0, "ok": 0, "skip": 0, "backup": 0, "missing": 0}
    print(f"dotfiles: {REPO}\nhome:     {HOME}\nos:       {this_os}{'  (dry run)' if args.dry_run else ''}\n")

    for e in entries:
        rel = e["path"]
        src, tgt = REPO / "home" / rel, HOME / rel
        if this_os not in e.get("os", ["linux", "macos"]):
            counts["skip"] += 1
            print(f"  skip     ~/{rel}  (not for {this_os})")
            continue
        if not src.exists():
            counts["missing"] += 1
            print(f"  MISSING  ~/{rel}  (not in repo)")
            continue
        if tgt.is_symlink() and os.path.realpath(tgt) == os.path.realpath(src):
            counts["ok"] += 1
            print(f"  ok       ~/{rel}")
            continue
        if os.path.lexists(tgt):
            dest = backup_root / rel
            counts["backup"] += 1
            print(f"  backup   ~/{rel}  ->  {dest}")
            if not args.dry_run:
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(tgt), str(dest))
        counts["link"] += 1
        print(f"  link     ~/{rel}")
        if not args.dry_run:
            tgt.parent.mkdir(parents=True, exist_ok=True)
            os.symlink(src, tgt, target_is_directory=src.is_dir())

    verb = "would link" if args.dry_run else "linked"
    print(f"\n{verb} {counts['link']}, already ok {counts['ok']}, backed up {counts['backup']}, "
          f"skipped {counts['skip']}, missing {counts['missing']}")
    return 1 if counts["missing"] else 0


if __name__ == "__main__":
    sys.exit(main())
